foyer-work/cdn-files

merlin_config.json
Reverts foyer-work/cdn-files#35
=> Revert "Update merlin_config.json"

merlin_config.json
- Adds class for twitter container
=> chore: add twitter container classname

merlin_config.json
=> white saturday

merlin_config.json
Reverts foyer-work/cdn-files#60
=> Revert "white saturday"

merlin_config.json
=> Fix Code Interpreter Copy

merlin_config.json
- added a flag to enable/disable unified chat
=> Added Unified Chat Flag

merlin_config.json
- Image chat tutorial more details url is changed
=> fix: image generation blog url slug changed

prompts/quill.json
Fix input extraction issue in quill
=> fix: extract text from input field

merlin_config.json
=> feat: new survey item

merlin_config.json
Turned off Survey Dialog Popup on Extension.
=> Turn off survey from extension

merlin_config.json
- Add flag for scraping subs on youtube frontend
=> FYR-2593: feat add scraping flag for youtube subs

wallflower/models.json
=> chore: add wallflower models

merlin_constants.json
Introduces new models from OpenAI - `o1-preview` & `o1-mini`.
Related PRs:
- https://github.com/foyer-work/arcane/pull/154
=> feat: O1 Preview & O1 Mini

merlin_constants.json
- add largeContext variable to models 
- true for 1.5 flash, haiku and 4o mini
=> feat: Large Context Mode (FYR-2717)

bonkers/models.json
Adding flux 1.1 pro in bonkers models
=> feat: add new bonkers flux model

wallflower/models.json
- Remove Ideogram v1
- Change Flux models name by removing (.1)
- Add speed
- Add bestFor
- Change tags
=> refactor: bonkers models list

bonkers/models.json, wallflower/models.json
- Add flux 1.1 pro in wallflower models
- Cost changes for ideogram and flux 1.1 pro in bonkers models and wallflower models
=> feat: add flux 1.1 pro in wallflower, cost changes for ideogram & flux 1.1 pro

wallflower/models.json
- Add Recraft V3 (red panda) model for wallflower and bonkers-magic
=> feat: add Recraft V3 model for wallflower

wallflower/models.json
- add if Inpainting is available for all models in wallflower models
=> refactor: add inpainting available field in wallflower models

wallflower/models.json
Replaced isInpaintingAvailable field with featureSupport to avoid confusion and separate multiple fields for multiple features.
=> refactor(wallflower): replace isInpaintAvailable with featureSupport

merlin_config.json
1. added a new config for chat gui to switch between "native" and "iframe" ui's
=> feat: native/iframe toggle

merlin_constants.json
The `deepseek-chat` (DeepSeek V3) model was recently set as the default for chat. However, users have [reported](https://merlin-ai.canny.io/bug-report/p/deepseek-3-decreased-speed
) that it responds slowly and occasionally gets stuck mid-response. After verifying these issues, this PR reverts the default model back to `gpt-3.5-turbo`.
Reverts default model changes introduced in: https://github.com/foyer-work/cdn-files/commit/b97ccfa42def9855368f5c1aac244000d51a5cbd
Arcane PR: https://github.com/foyer-work/arcane/pull/379
=> refactor: revert default model to `gpt-3.5-turbo`

merlin_config.json
blacklist paths added for saveToMerlin
=> feat: add saveToMerlin configuration 

wallflower/models.json, wallflower/styles.json
- Add new tags for bonkers models
- Remove bestFor field from models
- Rearrange models according to usage
- Add example images for bonkers styles
=> feat(bonkers): update models and styles 

merlin_constants.json
Move `o3-mini-high` near the top. Deepseek R1 right after that, then gemini etc.
=> change: update model importances

wallflower/models.json, wallflower/styles.json
Refactor Bonkers styles and models images
- use compressed images stored on gcs (wallflower-images) 
- served using imagekit
=> refactor(bonkers): use compressed images stored on gcs

merlin_constants.json
See https://github.com/foyer-work/arcane/pull/452
=> refactor: model costs updated

merlin_config.json
reverted native to iFrame in chat GUI
=> config: change chat GUI mode from native to iframe

wallflower/models.json
- new Hidream L1 model (fastest, cheap, best quality model)
- Hidream is optimised version of flux by Pruna AI
=> feat(bonkers): add HiDream L1 Fast model

bonkers-magic/models.json
- separate bonkers models from wallflower 
- new gpt-image-1 models
- remove flux schnell
=> feat(bonkers): new openai image models & separate models from wallflower

bonkers-magic/templates.json
new templates with metadata information - 
- product photoshoots
- make me bald
- watermark remover
**dependent on** - https://github.com/foyer-work/merlin-monorepo/pull/1967
=> feat(bonkers): add new templates 

bonkers-magic/models.json
- add ideogram v3 
- queryCost - 75
- backend PR - https://github.com/foyer-work/arcane/pull/599
=> feat(bonkers):add ideogram v3

bonkers-magic/templates.json
**New Templates**
- Humanize my pet
- Minecraft Style
- Pixar Style
- Simpson Style
=> feat(bonkers): add new templates for pet humanization and various style

bonkers-magic/models.json
update from GPT Image 1 to ChatGPT 4o
=> refactor(bonkers): update display name for gpt image models

wallflower/models.json
add defaultFree and defaultPro fields to wallflower models asked by mobile team
=> feat: add defaultFree and defaultPro fields to wallflower models

bonkers-magic/models.json
add bonkers featured models that needs to be shown initially before see more.
add isEnabled and isFeatured fields
=> feat(bonkers): models with additional tags and enablement status

bonkers-magic/templates.json
New key `showGeneratedImages` to render images sidepanel for templates accordingly
=> feat(bonkers): control to show generated images

bonkers-magic/models.json
add Google Imagen 4 model with updated icons
=> feat(bonkers): add Google Imagen 4 model with updated icons

bonkers-magic/templates.json
- Fix extra comma issues after values
=> fix(templates): comma issue for values

bonkers-magic/templates.json
- Enabled product photography template
=> refactor(bonkers): enable product photography template

bonkers-magic/image-models.json, bonkers-magic/models.json
- Added new image models including Remix, and Editor models
=> feat(bonkers): image models

bonkers-magic/models.json
- Fix google image gen model icon, earlier it was using Bonkers model icon
=> fix(bonkers): google image-gen model icon

bonkers-magic/models.json
- New thumbnail for Google Imagen 4 model
=> refactor(templates): Google Imagen 4 thumbnail

bonkers-magic/templates.json
Change in template's naming and new key field as `webName`, seperating names to render on Mobile & Web
=> refactor(templates): templates naming

bonkers-magic/templates.json
- Added `logo-wizard` template for logo generations.
- New schema changes for select params type and new param type added as `styles`
=> feat(templates): logo-wizard

bonkers-magic/templates.json
- Changed object key for logo-wizard for styles parameter
=> refactor: key change for logo wizard

merlin_constants.json
- Swap importance value for gpt-5-pro and gpt-4.1 for reordering in model selector
=> refactor(models): Swap importance value to reorder models
